//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shuttle.ESB.Modules {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class LoggingResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LoggingResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Shuttle.ESB.Modules.Logging.LoggingResources", typeof(LoggingResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [received correlation id] : &apos;{0}&apos;.
        /// </summary>
        public static string CorrelationIdReceived {
            get {
                return ResourceManager.GetString("CorrelationIdReceived", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TransportMessage with message type &apos;{0}&apos; and id &apos;{1}&apos; has been decompressed using &apos;{2}&apos;..
        /// </summary>
        public static string DecompressedMessage {
            get {
                return ResourceManager.GetString("DecompressedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TransportMessage with message type &apos;{0}&apos; and id &apos;{1}&apos; has been decrypted using &apos;{2}&apos;..
        /// </summary>
        public static string DecryptedMessage {
            get {
                return ResourceManager.GetString("DecryptedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deferred transport message with id &apos;{0}&apos; has been returned to the inbox work queue..
        /// </summary>
        public static string DeferredTransportMessageReturned {
            get {
                return ResourceManager.GetString("DeferredTransportMessageReturned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [acknowledged] : message type = &apos;{0}&apos; / message id = &apos;{1}&apos;.
        /// </summary>
        public static string MessageAcknowledged {
            get {
                return ResourceManager.GetString("MessageAcknowledged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transport message type &apos;{0}&apos; with id &apos;{1}&apos; has been assigned to a thread on this endpoint..
        /// </summary>
        public static string MessageAssigned {
            get {
                return ResourceManager.GetString("MessageAssigned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message type &apos;{0}&apos; with id &apos;{1}&apos; has been deserialized..
        /// </summary>
        public static string MessageDeserialized {
            get {
                return ResourceManager.GetString("MessageDeserialized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transport message type &apos;{0}&apos; with id &apos;{1}&apos; has already been handled..
        /// </summary>
        public static string MessageHandled {
            get {
                return ResourceManager.GetString("MessageHandled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message type &apos;{0}&apos; with id &apos;{1}&apos; invoking on handler &apos;{2}&apos;..
        /// </summary>
        public static string MessageHandlerInvoked {
            get {
                return ResourceManager.GetString("MessageHandlerInvoked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transport message type &apos;{0}&apos; with id &apos;{1}&apos; has already been assigned to another thread..
        /// </summary>
        public static string MessageIgnored {
            get {
                return ResourceManager.GetString("MessageIgnored", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (message handler is null).
        /// </summary>
        public static string MesssageHandlerNull {
            get {
                return ResourceManager.GetString("MesssageHandlerNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stream dequeued from queue &apos;{0}&apos;..
        /// </summary>
        public static string StreamDequeued {
            get {
                return ResourceManager.GetString("StreamDequeued", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [transport message header (received)] : {0} = {1}.
        /// </summary>
        public static string TransportHeaderReceived {
            get {
                return ResourceManager.GetString("TransportHeaderReceived", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TransportMessage with message type &apos;{0}&apos; and id &apos;{1}&apos; has been deserialized..
        /// </summary>
        public static string TransportMessageDeserialized {
            get {
                return ResourceManager.GetString("TransportMessageDeserialized", resourceCulture);
            }
        }
    }
}
